### ISSUE TITLE
Would you consider dual licensing (GPL/Apache)

### ISSUE THREAD

**Issue by Miles-Garnsey** [lwithers/minijks#2]
I am considering using minijks to parse JKS key/truststore files in the (OSS) [project](https://github.com/k8ssandra/k8ssandra-operator) I am currently working on. 

Unfortunately I've been advised that we aren't able to ship GPL dependancies. 

This is obviously a slightly cheeky question, but would you be willing to dual license this project under Apache and GPL so that I can look at using it?

**Comment by lwithers** [comment]
Hi Miles,

Actually I have drifted more towards the MIT licence myself, so sure thing, I think an update is in order.

**Comment by Miles-Garnsey** [comment]
That's amazing thanks @lwithers! MIT is compatible with Apache from my (limited) understanding so that'll be perfect!
